config/urls.py
# Django
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

# Terceros

# Propias
from finanzas_personales.apps.usuarios.views import IniciarSesion


urlpatterns = [
    path('', IniciarSesion.as_view(), name="inicio_sesion"),
    path('admin/', admin.site.urls),
    path('usuarios/', include('finanzas_personales.apps.usuarios.urls', namespace='usuarios')),
    path('movimientos/', include('finanzas_personales.apps.movimientos.urls', namespace='movimientos')),
    path('funcionalidades/', include('finanzas_personales.apps.funcionalidades.urls', namespace='funcionalidades')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finanzas_personales/apps/funcionalidades/urls.py
from django.urls import path

from .views import CalculadoraIntereses, Analitica

app_name = 'funcionalidades'

urlpatterns = [
    path('caluladora-intereses', CalculadoraIntereses.as_view(), name='calculadora_intereses'),
    path('analitica/', Analitica.as_view(), name='analitica'),

]

finanzas_personales/apps/movimientos/urls.py
from django.urls import path

from .views import RegistrarMovimiento

app_name = 'movimientos'

urlpatterns = [
    path('registrar', view=RegistrarMovimiento.as_view(), name='registrar'),
]

finanzas_personales/apps/usuarios/urls.py
from django.urls import path

from .views import Registro, IniciarSesion, logout_view

app_name = 'usuarios'

urlpatterns = [
    path('registro/', Registro.as_view(), name='registro'),
    path('iniciar_sesion/', IniciarSesion.as_view(), name='iniciar_sesion'),
    #path('pagina_principal/', PaginaPrincipal.as_view(), name='pagina_principal'),
    path('cerrar_sesion/', logout_view, name='cerrar_sesion'),
]

finanzas_personales/apps/funcionalidades/models.py
from django.db import models

# Create your models here.

finanzas_personales/apps/movimientos/models.py
# Modulos Django
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django_currentuser.db.models import CurrentUserField
  
# Modulos de plugin externos
from decimal import Decimal
# Modulos de otras apps

# Modulos internos de la app

# Create your models here.
class Tipo(models.Model):
    nombre = models.CharField(max_length=15, verbose_name="Nombre movimiento", blank=False, null=False)

    class Meta:
        ordering = ('nombre',)
    
    def __str__(self):
        return self.nombre

class Movimiento(models.Model):
    usuario = CurrentUserField(related_name="movimiento_usuario")
    tipo = models.ForeignKey(Tipo, verbose_name="Tipo movimiento", related_name="movimiento_tipo", on_delete=models.CASCADE, blank=False, null=False)
    cantidad = models.DecimalField(decimal_places=2, max_digits=12, validators=[MaxValueValidator(Decimal('100000000000.00')), MinValueValidator(Decimal('0.00'))])
    descripcion = models.CharField(max_length=30, verbose_name="Descripción", blank=False, null=False)
    fecha_inscripcion = models.DateTimeField(auto_now_add=True)

    @staticmethod
    def obtener_suma_movimientos(id_usuario, tipo):
        from django.db.models import Sum
        movimiento = Movimiento.objects.filter(tipo__nombre=tipo, usuario__pk=id_usuario).aggregate(total=Sum('cantidad'))
        
      
        if  movimiento['total']:
            return movimiento['total']
        else:
            return 0

finanzas_personales/apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
# Create your models here.

class Usuario(AbstractUser):
    email = models.EmailField(
        verbose_name='email address',
        unique=True,
        error_messages={
            'unique': 'Ya existe un usuario con ese correo.'
        }
    )

    telefono_regex = RegexValidator(
        regex=r'\+?1?\d{9,15}$',
        message="El numero debe tener entre 9 y 15 caracteres."
    )
    telefono = models.CharField(validators=[telefono_regex], max_length=17, blank=True)
    fecha_nacimiento = models.DateTimeField(blank=False, null=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return self.first_name+" "+self.last_name
    

    def obtener_movimientos_anio_mes(self, anio, mes, tipo):
        movimientos = self.movimiento_usuario.filter(tipo__nombre=tipo, fecha_inscripcion__year=anio, fecha_inscripcion__month=mes)
        return movimientos
    
    def obtener_suma_cantidad_movimientos_anio_mes(self, anio, mes, tipo):
        from django.db.models import Sum
        return self.obtener_movimientos_anio_mes(anio, mes, tipo).aggregate(total=Sum('cantidad'))
    
    def obtener_suma_cantidad_movimientos(self):
        from django.db.models import Sum
        lista_retorno = []
        ingresos = self.movimiento_usuario.filter(tipo__nombre='Ingreso').aggregate(total=Sum('cantidad'))
        gastos = self.movimiento_usuario.filter(tipo__nombre='Gasto').aggregate(total=Sum('cantidad'))
        if ingresos['total'] and gastos['total']:
            lista_retorno = [ {
                "category": "ingresos",
                "cantidad": float(ingresos['total'])},
                {"grafica_tortas": "gastos",
                "cantidad": float(gastos['total'])}
            ]
        return lista_retorno
    
    def obtener_rendimientos_rango_fecha(self, fecha_inicio, fecha_fin):
        anio_inicio = fecha_inicio.year
        mes_inicio = fecha_inicio.month
        
        
        mes_fin = fecha_fin.month
        
        lista_meses = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']
        lista_retorno = []
        while mes_inicio <= mes_fin:
            ingresos = self.obtener_suma_cantidad_movimientos_anio_mes(anio=anio_inicio, mes=mes_inicio, tipo='Ingreso')
            gastos = self.obtener_suma_cantidad_movimientos_anio_mes(anio=anio_inicio, mes=mes_inicio, tipo='Gasto')
            if ingresos['total'] and gastos['total']:
                lista_retorno.append({
                    'category': lista_meses[mes_inicio-1],
                    'ingresos': int(ingresos['total']/1000),
                    'gastos': int(gastos['total']/1000),
                })           
            mes_inicio += 1
        for l in lista_retorno:
            print(l)  

        return lista_retorno
    
    
'''
    [
    {
        category: 'Place #1',
        ingresos: 40,
        gastos: 55,        
    },
    {
        category: 'Place #2',
        ingresos: 30,
        gastos: 78,       
    },
    {
        category: 'Place #3',
        ingresos: 27,
        gastos: 40,        
    },
    {
        category: 'Place #4',
        ingresos: 50,
        gastos: 33,        
    }
]'''

finanzas_personales/apps/movimientos/forms.py
# Modulos Django
from django import forms

# Modulos de plugin externos

# Modulos de otras apps

# Modulos internos de la app
from .models import Movimiento

class RegistrarMovimiento(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(RegistrarMovimiento, self).__init__(*args, **kwargs)
        self.fields['cantidad'].label = ''
        self.fields['descripcion'].label = ''
        self.fields['cantidad'].widget.attrs['placeholder'] = 'Cantidad'
        self.fields['descripcion'].widget.attrs['placeholder'] = 'Descripcion'

    class Meta:
        model = Movimiento
        fields = ('tipo', 'cantidad', 'descripcion')

finanzas_personales/apps/usuarios/forms.py
# Django
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms

# Terceros
from tempus_dominus.widgets import DatePicker

# Propias
from finanzas_personales.apps.usuarios.models import Usuario



class FormularioInicioSesion(AuthenticationForm):
    username = forms.EmailField(error_messages={
        'required': 'Este campo es requerido',
        'invalid': 'Introduzca un correo valido'
    })
    #password = forms.PasswordInput(label="Contraseña")

    def __init__(self, *args, **kwargs):
        super(FormularioInicioSesion, self).__init__(*args, **kwargs)
        print(self.fields)
        self.fields['username'].widget.attrs['placeholder'] = 'Correo electrónico'
        self.fields['password'].widget.attrs['placeholder'] = 'Contraseña'
        self.fields['username'].label = ''
        self.fields['password'].label = ''

    class Meta:
        model = Usuario
        fields = ('username', 'password')
        

class FormularioCreacionUsuario(UserCreationForm):
    fecha_nacimiento = forms.DateField(
        widget=DatePicker(
            options={
                'locale': 'es',
                'format': 'YYYY-MM-DD',
                'minDate': '1900-01-1',
                #'maxDate': '2017-01-20',
            },
            attrs={
                'append': 'fa fa-calendar',
                'icon_toggle': False,                
            },
        ),
       
    )
    def __init__(self, *args, **kwargs):
        super(FormularioCreacionUsuario, self).__init__(*args, **kwargs)
        for field in self.fields:            
            self.fields[field].help_text = ""
        
        self.fields['first_name'].label = 'Nombres'
        self.fields['last_name'].label = 'Apellidos'
        self.fields['email'].label = 'Correo electrónico'
        self.fields['telefono'].label = 'Teléfono'
        self.fields['password1'].label = 'Contraseña'
        self.fields['password2'].label = 'Confirmación de contraseña'
    class Meta:
        model = Usuario
        fields = ('first_name', 'last_name', 'email', 'telefono', 'fecha_nacimiento', 'password1', 'password2')
       

finanzas_personales/apps/funcionalidades/views.py
# Modulos Django
from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
# Modulos de plugin externos

# Modulos de otras apps

# Modulos internos de la app

# Create your views here.

class CalculadoraIntereses(LoginRequiredMixin, TemplateView):
    template_name = 'funcionalidades/calculadora_intereses.html'
    success_url = reverse_lazy('funcionalidades:calculadora_intereses')

    def get_context_data(self, **kwargs):
        context = super(CalculadoraIntereses, self).get_context_data(**kwargs)
    
        if self.request.GET:
            cantidad = float(self.request.GET['cantidad'])
            cuotas = int(self.request.GET['cuotas'])
            tasa_interes = float(self.request.GET['tasa_interes'])

            context['cuotas_mensuales'] = round((cantidad/cuotas)*tasa_interes, 2)
            
            #print("##{}-{}-{}".format(cuotas_mensuales, cuotas, tasa_interes))
        return context

class Analitica(LoginRequiredMixin, TemplateView):
    template_name = 'funcionalidades/analitica.html'
   
    def get_context_data(self, **kwargs):
        from datetime import timezone
        import datetime
        context = super(Analitica, self).get_context_data(**kwargs)
        usuario =  self.request.user
        ingresos = usuario.obtener_movimientos_anio_mes(anio=2020, mes=10, tipo='Ingreso')
        gastos = usuario.obtener_movimientos_anio_mes(anio=2020, mes=10, tipo='Gasto')


        fecha_inicio = datetime.date(2020, 1, 1)
        fecha_fin = datetime.datetime.now()

        context['movimientos'] = usuario.obtener_rendimientos_rango_fecha(fecha_inicio, fecha_fin)
        context['tortas'] = usuario.obtener_suma_cantidad_movimientos()
        
            
        return context

finanzas_personales/apps/movimientos/views.py
# Modulos Django
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

# Modulos de plugin externos
from rest_framework.response import Response
from rest_framework.views import APIView

# Modulos de otras apps

# Modulos internos de la app
from .forms import RegistrarMovimiento
from .models import Movimiento, Tipo

# Create your views here.
class RegistrarMovimiento(CreateView,LoginRequiredMixin):
    model = Movimiento
    form_class = RegistrarMovimiento
    template_name = 'movimientos/index.html'
    success_url = reverse_lazy('movimientos:registrar')

    def get_context_data(self, **kwargs):
        context = super(RegistrarMovimiento, self).get_context_data(**kwargs)
        movimientos = Movimiento.objects.filter(usuario=self.request.user).order_by('-fecha_inscripcion')
        context['movimientos'] = movimientos
        #scroto(self.request)
        return context





def scroto(request):
    import numpy as np
    lista_gastos = [56715,
        454225,
        307300,
        310000,
        910725,
        700725,
        1035725,
        215500,
        205950,
        584926,
        252320,
        222180]

    
    usuario = request.user
    mes = 1
    while mes<=12:
        usuario
        ingreso = Tipo.objects.get(nombre="Ingreso")
        Movimiento.objects.create(usuario=usuario, tipo=ingreso, cantidad=500000, descripcion='Pago Nomina')

        gasto = Tipo.objects.get(nombre="Gasto")
        dia = 1
        aux = lista_gastos[mes-1]
        print("################## MES: ", mes)
        while dia <= 28 and aux>0:
            if dia != 28:
                if aux >= 10000:
                    cantidad = np.random.randint(10000, aux)
                else:
                    cantidad = aux
                aux -= cantidad
            else:
                cantidad = aux
            
            Movimiento.objects.create(usuario=usuario, tipo=gasto, cantidad=cantidad, descripcion='Gasto')

            print("         cantidad: ", cantidad)            
            dia += 1

        mes += 1

    

finanzas_personales/apps/usuarios/views.py
# Modulos Django
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout

# Modulos de plugin externos

# Modulos de otras apps
from finanzas_personales.apps.usuarios.models import Usuario
from finanzas_personales.apps.movimientos.views import RegistrarMovimiento
# Modulos internos de la app
from .forms import FormularioCreacionUsuario, FormularioInicioSesion


class Registro(CreateView):
    model = Usuario
    form_class = FormularioCreacionUsuario
    template_name = 'usuarios/registro.html'
    success_url = reverse_lazy('usuarios:iniciar_sesion')

    def form_valid(self, form):
        usuario = form.save(commit=False)
        usuario.username = form.instance.email
        usuario.save()
        return super(Registro, self).form_valid(form)

class IniciarSesion(LoginView):    
    template_name = 'usuarios/iniciar_sesion.html'    
    form_class = FormularioInicioSesion
    def dispatch(self, request, *args, **kwargs):        
        if request.user.is_authenticated:            
            return redirect('movimientos:registrar')
        return super(IniciarSesion, self).dispatch(request, *args, **kwargs)

#class PaginaPrincipal(LoginRequiredMixin, TemplateView):
#    template_name = 'usuarios/pagina_principal/index.html'
    
def logout_view(request):
    logout(request)
    return redirect('usuarios:iniciar_sesion')

finanzas_personales/templates/base.html
{% load static %}
{% load bootstrap4 %}


<!DOCTYPE html>
<html lang="es">
<head>

    <meta charset="utf-8" />
    <title>
        {% block titulo %}
            Home
        {% endblock titulo %}
    </title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    {% block css %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap-grid.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap-grid.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap-reboot.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap-reboot.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/custom/barra_navegacion/barra_navegacion.css' %}">
    {% endblock css %}

    {% block extracss %}    
    {% endblock extracss %}

    {{ form.media }}
</head>
<body>   
<div>    
    <!-- begin breadcrumb -->
    {% block header %}
     
            <div class="container-navbar">
                <header class="header"></header>
                <input type="checkbox" name="" id="check">
                <label for="check" href="javascript:void(0);">&#9776;</label>     
                <div class="menu-background"></div>    
                                  
                <nav class="menu">
                    <div class="menu-header">
                        <img src="{{MEDIA_URL}}iconos/logo.png" alt="" class="w-50 h-50 mt-4 ml-4">
                        <h6 class="text-center mt-3">{{request.user}}</h6>
                    </div> 
                    <ul class="m-0 pl-2 pt-0 pr-0 pb-0 container-options">
                        <li><i class="fa fa-money icons"></i><a href="{% url 'movimientos:registrar'%}" class="text-decoration-none">Movimientos</a></li>
                        <li><i class="fa fa-line-chart icons"></i><a href="" class="text-decoration-none">Gráficos</a></li>
                        <li><i class="fa fa-flag icons icons"></i><a href="" class="text-decoration-none">Retos</a></li>
                        <li><i class="fa fa fa-gear icons"></i><a href="" class="text-decoration-none">Configuración</a></li>
                        <li><i class="fa fa-cubes icons"></i><a href="{% url 'funcionalidades:analitica'%}" class="text-decoration-none">Analitica</a></li>  
                        <li><i class="fa fa-calculator icons"></i><a href="{% url 'funcionalidades:calculadora_intereses'%}" class="text-decoration-none">Calculadora</a></li>                      
                        <li><i class="fa fa-star icons"></i><a href="{% url 'funcionalidades:analitica'%}" class="text-decoration-none">Actualizate a Premium</a></li>      
                        <li><i class="fa fa-user-times icons"></i><a href="{% url 'usuarios:cerrar_sesion'%}" class="text-decoration-none">Cerra sesion</a></li>
                    </ul>
                </nav>
            </div>
        
    {% endblock header%}

      
    <h1 class="page-header mb-3">       
        {% block titulo_pagina %}
        {% endblock titulo_pagina %}
    </h1>        
    
    {% block contenido %}
        <div class="panel panel-inverse">
            <div class="panel-body">
                {% block contenido_panel %}{% endblock contenido_panel %}
            </div>
        </div>
    {% endblock contenido %} 
    {% block contenido_botones %}{% endblock contenido_botones %}   
    
    <!-- end scroll to top btn -->   
</div>

<script>
    $(document).ready(function() {
        {% for msg in messages %}
            $(document).ready(function(){
                setTimeout(function() {
                    toastr.options = {
                        "allowHtml": true,
                        "positionClass": "toast-bottom-right",
                        "preventDuplicates": true,
                        "newestOnTop": true,
                        "closeButton": true,
                        "progressBar": true,
                        "showEasing": "swing",
                        "extendedTimeOut": 5000,
                        "timeOut": 5000,
                        "body-output-type": "trustedHtml"
                    };
                    toastr["{{ msg.tags }}"]("{{msg|safe}}")
                },500);
            });
        {% endfor %}
    });
    $('form').attr('autocomplete','off');
  
</script>

{% block js %}
    <script src="{% static 'js/bootstrap/bootstrap.js'%}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.bundle.js'%}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.min.js'%}"></script>    
{% endblock js %}

{% block extrajs %}
{% endblock extrajs %}

finanzas_personales/templates/base_user.html
{% load static %}
{% load bootstrap4 %}


<!DOCTYPE html>
<html lang="es">
<head>

    <meta charset="utf-8" />
    <title>
        {% block titulo %}
            Home
        {% endblock titulo %}
    </title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap-grid.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap-grid.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap-reboot.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap-reboot.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}">       
    {% endblock css %}

    {% block extracss %}    
    {% endblock extracss %}

    {{ form.media }}
</head>
<body>    
<div>

    {% block contenido_panel %}{% endblock contenido_panel %}    
    <!-- end scroll to top btn -->   
</div>

<script>
    $(document).ready(function() {
        {% for msg in messages %}
            $(document).ready(function(){
                setTimeout(function() {
                    toastr.options = {
                        "allowHtml": true,
                        "positionClass": "toast-bottom-right",
                        "preventDuplicates": true,
                        "newestOnTop": true,
                        "closeButton": true,
                        "progressBar": true,
                        "showEasing": "swing",
                        "extendedTimeOut": 5000,
                        "timeOut": 5000,
                        "body-output-type": "trustedHtml"
                    };
                    toastr["{{ msg.tags }}"]("{{msg|safe}}")
                },500);
            });
        {% endfor %}
    });
    $('form').attr('autocomplete','off');
</script>

{% block js %}
    <script src="{% static 'js/bootstrap/bootstrap.js'%}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.bundle.js'%}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.min.js'%}"></script>    
{% endblock js %}

{% block extrajs %}
{% endblock extrajs %}